# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/r7/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/r7

PRODUCT_COPY_FILES += \
    vendor/samsung/r7/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/samsung/r7/proprietary/vendor/etc/floating_feature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/floating_feature.xml \
    vendor/samsung/r7/proprietary/vendor/etc/gnss/gps.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.xml \
    vendor/samsung/r7/proprietary/vendor/etc/init/init.baseband.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.baseband.rc \
    vendor/samsung/r7/proprietary/vendor/etc/init/init.gps.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps.rc \
    vendor/samsung/r7/proprietary/vendor/etc/init/vendor.samsung.hardware.gnss@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.gnss@2.0-service.rc \
    vendor/samsung/r7/proprietary/vendor/etc/media_codecs_performance.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance.xml \
    vendor/samsung/r7/proprietary/vendor/etc/mixer_gains.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_gains.xml \
    vendor/samsung/r7/proprietary/vendor/etc/mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths.xml \
    vendor/samsung/r7/proprietary/vendor/etc/plmn_se13.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_se13.bin \
    vendor/samsung/r7/proprietary/vendor/etc/sensor/lhd.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensor/lhd.conf \
    vendor/samsung/r7/proprietary/vendor/firmware/APBargeIn_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APBargeIn_AUDIO_SLSI.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/APBiBF_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APBiBF_AUDIO_SLSI.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/APDV_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APDV_AUDIO_SLSI.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/APSV_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APSV_AUDIO_SLSI.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/AP_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/AP_AUDIO_SLSI.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/CP_AUDIO_SLSI_SEA.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/CP_AUDIO_SLSI_SEA.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/CP_AUDIO_SLSI_SWA.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/CP_AUDIO_SLSI_SWA.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/SoundBoosterParam.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SoundBoosterParam.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/WithLightFixNoBN.SDNNmodel:$(TARGET_COPY_OUT_VENDOR)/firmware/WithLightFixNoBN.SDNNmodel \
    vendor/samsung/r7/proprietary/vendor/firmware/a2dpcom.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a2dpcom.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/a96t365_r7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a96t365_r7.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/bcm4361B2_murata.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4361B2_murata.hcd \
    vendor/samsung/r7/proprietary/vendor/firmware/bcm4361B2_semco.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4361B2_semco.hcd \
    vendor/samsung/r7/proprietary/vendor/firmware/bcmdhd_clm.blob:$(TARGET_COPY_OUT_VENDOR)/firmware/bcmdhd_clm.blob \
    vendor/samsung/r7/proprietary/vendor/firmware/bcmdhd_mfg.bin_b0:$(TARGET_COPY_OUT_VENDOR)/firmware/bcmdhd_mfg.bin_b0 \
    vendor/samsung/r7/proprietary/vendor/firmware/bcmdhd_mfg.bin_b2:$(TARGET_COPY_OUT_VENDOR)/firmware/bcmdhd_mfg.bin_b2 \
    vendor/samsung/r7/proprietary/vendor/firmware/bcmdhd_mon.bin_b2:$(TARGET_COPY_OUT_VENDOR)/firmware/bcmdhd_mon.bin_b2 \
    vendor/samsung/r7/proprietary/vendor/firmware/bcmdhd_sta.bin_b0:$(TARGET_COPY_OUT_VENDOR)/firmware/bcmdhd_sta.bin_b0 \
    vendor/samsung/r7/proprietary/vendor/firmware/bcmdhd_sta.bin_b2:$(TARGET_COPY_OUT_VENDOR)/firmware/bcmdhd_sta.bin_b2 \
    vendor/samsung/r7/proprietary/vendor/firmware/calliope_dram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_dram.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/calliope_iva.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_iva.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/calliope_sram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_sram.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/dax_param.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dax_param.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/default_configuration.hfd.cfg.json:$(TARGET_COPY_OUT_VENDOR)/firmware/default_configuration.hfd.cfg.json \
    vendor/samsung/r7/proprietary/vendor/firmware/fimc_is_lib.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_lib.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/fimc_is_rta_2l2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_rta_2l2.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/fimc_is_rta_imx333.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_rta_imx333.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/iva20_rt-lhotse.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/iva20_rt-lhotse.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc_fw.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/nfc/libpn553_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/nfc/libpn553_fw.so \
    vendor/samsung/r7/proprietary/vendor/firmware/nvram.txt_murata_r041_b2:$(TARGET_COPY_OUT_VENDOR)/firmware/nvram.txt_murata_r041_b2 \
    vendor/samsung/r7/proprietary/vendor/firmware/nvram.txt_r02a_b2:$(TARGET_COPY_OUT_VENDOR)/firmware/nvram.txt_r02a_b2 \
    vendor/samsung/r7/proprietary/vendor/firmware/nvram.txt_r02b_b2:$(TARGET_COPY_OUT_VENDOR)/firmware/nvram.txt_r02b_b2 \
    vendor/samsung/r7/proprietary/vendor/firmware/ois_fw_dom.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ois_fw_dom.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/ois_fw_sec.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ois_fw_sec.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/param_ti.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/param_ti.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/pp_cfg.json:$(TARGET_COPY_OUT_VENDOR)/firmware/pp_cfg.json \
    vendor/samsung/r7/proprietary/vendor/firmware/setfile_2l2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_2l2.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/setfile_3l6.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_3l6.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/setfile_3m3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_3m3.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/setfile_imx333.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_imx333.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/setfile_imx616.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_imx616.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/spkamp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/spkamp.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/sv.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sv.bin \
    vendor/samsung/r7/proprietary/vendor/firmware/tracker_cfg.json:$(TARGET_COPY_OUT_VENDOR)/firmware/tracker_cfg.json \
    vendor/samsung/r7/proprietary/vendor/firmware/vts.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/vts.bin

PRODUCT_PACKAGES += \
    camera.exynos9810 \
    gatekeeper.exynos9810 \
    gralloc.exynos9810 \
    hwcomposer.exynos9810 \
    memtrack.exynos9810 \
    libbauthserver \
    libbauthtzcommon \
    libexynoscamera3 \
    libexynosdisplay \
    sensors.sensorhub \
    libaudioeffectoffload \
    audio.primary.exynos9810 \
    libaudioproxy \
    librecordalive \
    libswdap \
    android.hardware.gnss@2.0-impl \
    gps.default \
    vendor.samsung.hardware.gnss@2.0-impl \
    libsec-ril \
    libwrappergps \
    gpsd \
    lhd \
    vendor.samsung.hardware.gnss@2.0-service
